package database

import (
	"context"
	"crypto/rand"
	"crypto/sha1"
	"database/sql"
	"fmt"
	"time"

	"github.com/lib/pq"
)

type PostgreSQL struct {
	db *sql.DB
}

type User struct {
	ID        int       `json:"id"`
	Login     string    `json:"login"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Mail      string    `json:"mail"`
	Status    int       `json:"status"`
	CreatedOn time.Time `json:"created_on"`
	UpdatedOn time.Time `json:"updated_on"`
	APIKey    string    `json:"api_key,omitempty"`
}

type Project struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Identifier  string `json:"identifier"`
	Description string `json:"description"`
	Status      int    `json:"status"`
}

type Issue struct {
	ID           int        `json:"id"`
	Subject      string     `json:"subject"`
	Description  string     `json:"description"`
	StatusID     int        `json:"status_id"`
	PriorityID   int        `json:"priority_id"`
	ProjectID    int        `json:"project_id"`
	TrackerID    int        `json:"tracker_id"`
	AuthorID     int        `json:"author_id"`
	AssignedToID *int       `json:"assigned_to_id"`
	CreatedOn    time.Time  `json:"created_on"`
	UpdatedOn    time.Time  `json:"updated_on"`
	DueDate      *time.Time `json:"due_date"`
}

func NewPostgreSQL(connectionString string) (*PostgreSQL, error) {
	db, err := sql.Open("postgres", connectionString)
	if err != nil {
		return nil, fmt.Errorf("failed to open database connection: %w", err)
	}

	// Configure connection pool
	db.SetMaxOpenConns(25)
	db.SetMaxIdleConns(5)
	db.SetConnMaxLifetime(5 * time.Minute)

	// Test connection
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := db.PingContext(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	return &PostgreSQL{db: db}, nil
}

func (p *PostgreSQL) Close() error {
	return p.db.Close()
}

// PingContext pings the database to check connectivity
func (p *PostgreSQL) PingContext(ctx context.Context) error {
	return p.db.PingContext(ctx)
}

// QueryRowContext executes a query that is expected to return at most one row
func (p *PostgreSQL) QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row {
	return p.db.QueryRowContext(ctx, query, args...)
}

// QueryContext executes a query that returns multiple rows
func (p *PostgreSQL) QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error) {
	return p.db.QueryContext(ctx, query, args...)
}

// ExecContext executes a query without returning rows
func (p *PostgreSQL) ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {
	return p.db.ExecContext(ctx, query, args...)
}

// AuthenticateUser authenticates user against Redmine PostgreSQL database
func (p *PostgreSQL) AuthenticateUser(ctx context.Context, username, password string) (*User, error) {
	query := `
		SELECT 
			u.id, u.login, u.firstname, u.lastname, 
			u.hashed_password, u.salt, u.status,
			u.created_on, u.updated_on,
			t.value as api_key, t.created_on as api_key_created
		FROM users u
		LEFT JOIN tokens t ON u.id = t.user_id AND t.action = 'api' AND t.value IS NOT NULL
		WHERE u.login = $1 AND u.status = 1
	`

	var user User
	var hashedPassword, salt string
	var apiKey sql.NullString
	var apiKeyCreated sql.NullTime

	err := p.db.QueryRowContext(ctx, query, username).Scan(
		&user.ID, &user.Login, &user.Firstname, &user.Lastname,
		&hashedPassword, &salt, &user.Status,
		&user.CreatedOn, &user.UpdatedOn,
		&apiKey, &apiKeyCreated,
	)

	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("invalid username or password")
		}
		return nil, fmt.Errorf("database query failed: %w", err)
	}

	// Set mail to empty string since we don't fetch it from database
	user.Mail = ""

	// Set API key from nullable string
	if apiKey.Valid {
		user.APIKey = apiKey.String
	} else {
		user.APIKey = ""
	}

	// Verify password using Redmine's format: sha1(salt + sha1(password))
	if !p.verifyRedminePassword(password, hashedPassword, salt) {
		return nil, fmt.Errorf("invalid username or password")
	}

	// Note: API keys are generated by Redmine itself when user first accesses their API key
	// We just read the existing API key from the tokens table

	return &user, nil
}

// verifyRedminePassword verifies password using Redmine's hashing algorithm
func (p *PostgreSQL) verifyRedminePassword(password, hashedPassword, salt string) bool {
	// Redmine password hashing: sha1(salt + sha1(password))
	innerHash := fmt.Sprintf("%x", sha1.Sum([]byte(password)))
	outerHash := fmt.Sprintf("%x", sha1.Sum([]byte(salt+innerHash)))
	return outerHash == hashedPassword
}

// GenerateAPIKey generates a new API key for the user
func (p *PostgreSQL) GenerateAPIKey(ctx context.Context, userID int) (string, error) {
	// First, delete any existing API tokens for this user (matching Redmine's behavior)
	deleteQuery := `DELETE FROM tokens WHERE user_id = $1 AND action = 'api'`
	_, err := p.db.ExecContext(ctx, deleteQuery, userID)
	if err != nil {
		return "", fmt.Errorf("failed to delete existing API tokens: %w", err)
	}

	// Generate 40-character API key (same format as Redmine)
	apiKey := generateRandomString(40)

	// Store the new API key in the tokens table
	insertQuery := `
		INSERT INTO tokens (user_id, action, value, created_on, updated_on)
		VALUES ($1, 'api', $2, NOW(), NOW())
		RETURNING value
	`

	var returnedKey string
	err = p.db.QueryRowContext(ctx, insertQuery, userID, apiKey).Scan(&returnedKey)
	if err != nil {
		return "", fmt.Errorf("failed to store API key: %w", err)
	}

	return returnedKey, nil
}

// GetUserByID retrieves user by ID
func (p *PostgreSQL) GetUserByID(ctx context.Context, userID int) (*User, error) {
	query := `
		SELECT 
			u.id, u.login, u.firstname, u.lastname, 
			COALESCE(ea.address, '') as mail, u.status,
			u.created_on, u.updated_on,
			t.value as api_key
		FROM users u
		LEFT JOIN email_addresses ea ON u.id = ea.user_id AND ea.is_default = true
		LEFT JOIN tokens t ON u.id = t.user_id AND t.action = 'api'
		WHERE u.id = $1 AND u.status = 1
	`

	var user User
	var apiKey sql.NullString
	err := p.db.QueryRowContext(ctx, query, userID).Scan(
		&user.ID, &user.Login, &user.Firstname, &user.Lastname, &user.Mail, &user.Status,
		&user.CreatedOn, &user.UpdatedOn, &apiKey,
	)

	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found")
		}
		return nil, fmt.Errorf("database query failed: %w", err)
	}

	// Set API key from nullable string
	if apiKey.Valid {
		user.APIKey = apiKey.String
	} else {
		user.APIKey = ""
	}

	return &user, nil
}

// GetUserProjects retrieves projects accessible by the user
func (p *PostgreSQL) GetUserProjects(ctx context.Context, userID int) ([]*Project, error) {
	query := `
		SELECT DISTINCT p.id, p.name, p.identifier, p.description, p.status
		FROM projects p
		JOIN members m ON p.id = m.project_id
		WHERE m.user_id = $1 AND p.status = 1
		ORDER BY p.name
	`

	rows, err := p.db.QueryContext(ctx, query, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to query projects: %w", err)
	}
	defer rows.Close()

	var projects []*Project
	for rows.Next() {
		var project Project
		err := rows.Scan(&project.ID, &project.Name, &project.Identifier, &project.Description, &project.Status)
		if err != nil {
			return nil, fmt.Errorf("failed to scan project: %w", err)
		}
		projects = append(projects, &project)
	}

	return projects, nil
}

// GetUserIssues retrieves issues accessible by the user with optimized query
func (p *PostgreSQL) GetUserIssues(ctx context.Context, userID int, limit, offset int, filters map[string]string) ([]*Issue, int, error) {
	// Build WHERE clause based on filters
	whereClause := "WHERE i.project_id IN (SELECT DISTINCT m.project_id FROM members m WHERE m.user_id = $1 AND m.project_id IN (SELECT id FROM projects WHERE status = 1))"
	args := []interface{}{userID}
	argIndex := 2

	if statusID, ok := filters["status_id"]; ok && statusID != "" {
		whereClause += fmt.Sprintf(" AND i.status_id = $%d", argIndex)
		args = append(args, statusID)
		argIndex++
	}

	if projectID, ok := filters["project_id"]; ok && projectID != "" {
		whereClause += fmt.Sprintf(" AND i.project_id = $%d", argIndex)
		args = append(args, projectID)
		argIndex++
	}

	if assignedToID, ok := filters["assigned_to_id"]; ok && assignedToID != "" {
		if assignedToID == "me" {
			whereClause += fmt.Sprintf(" AND i.assigned_to_id = $%d", argIndex)
			args = append(args, userID)
		} else {
			whereClause += fmt.Sprintf(" AND i.assigned_to_id = $%d", argIndex)
			args = append(args, assignedToID)
		}
		argIndex++
	}

	// Count query
	countQuery := fmt.Sprintf(`
		SELECT COUNT(*)
		FROM issues i
		%s
	`, whereClause)

	var totalCount int
	err := p.db.QueryRowContext(ctx, countQuery, args...).Scan(&totalCount)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to count issues: %w", err)
	}

	// Main query
	query := fmt.Sprintf(`
		SELECT i.id, i.subject, i.description, i.status_id, i.priority_id,
			   i.project_id, i.tracker_id, i.author_id, i.assigned_to_id,
			   i.created_on, i.updated_on, i.due_date
		FROM issues i
		%s
		ORDER BY i.updated_on DESC
		LIMIT $%d OFFSET $%d
	`, whereClause, argIndex, argIndex+1)

	args = append(args, limit, offset)

	rows, err := p.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to query issues: %w", err)
	}
	defer rows.Close()

	var issues []*Issue
	for rows.Next() {
		var issue Issue
		err := rows.Scan(
			&issue.ID, &issue.Subject, &issue.Description, &issue.StatusID, &issue.PriorityID,
			&issue.ProjectID, &issue.TrackerID, &issue.AuthorID, &issue.AssignedToID,
			&issue.CreatedOn, &issue.UpdatedOn, &issue.DueDate,
		)
		if err != nil {
			return nil, 0, fmt.Errorf("failed to scan issue: %w", err)
		}
		issues = append(issues, &issue)
	}

	return issues, totalCount, nil
}

// GetIssueSubjects fetches issue subjects by IDs from the database
// This is used to enrich time entries with issue subjects without making multiple API calls
func (p *PostgreSQL) GetIssueSubjects(ctx context.Context, issueIDs []int) (map[int]string, error) {
	if len(issueIDs) == 0 {
		return make(map[int]string), nil
	}

	// Build query with IN clause
	query := `
		SELECT id, subject 
		FROM issues 
		WHERE id = ANY($1)
	`

	rows, err := p.db.QueryContext(ctx, query, pq.Array(issueIDs))
	if err != nil {
		return nil, fmt.Errorf("failed to query issue subjects: %w", err)
	}
	defer rows.Close()

	subjects := make(map[int]string)
	for rows.Next() {
		var id int
		var subject string
		if err := rows.Scan(&id, &subject); err != nil {
			return nil, fmt.Errorf("failed to scan issue subject: %w", err)
		}
		subjects[id] = subject
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating issue subjects: %w", err)
	}

	return subjects, nil
}

// generateRandomString generates a cryptographically secure random string of specified length
func generateRandomString(length int) string {
	const charset = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, length)

	// Use crypto/rand for secure random generation
	randomBytes := make([]byte, length)
	_, err := rand.Read(randomBytes)
	if err != nil {
		// Fallback to time-based generation if crypto/rand fails
		for i := range b {
			b[i] = charset[time.Now().UnixNano()%int64(len(charset))]
		}
		return string(b)
	}

	for i := range b {
		b[i] = charset[randomBytes[i]%byte(len(charset))]
	}
	return string(b)
}
